name: Page Monitor

on:
  schedule:
    - cron: "* * * * *"   # har 1 minute run hoga
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - run: pip install requests
      
      - run: python monitor.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
